version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/src
hooks:
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 180
      runas: root
      ignoreErrors: false
