version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/src
hooks:
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 180
  AfterInstall:
    - location: scripts/start-container.sh
      timeout: 180
