version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/src
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 180
      runas: root
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 180
      runas: root
  # ApplicationStart:
  #   - location: scripts/application-start.sh
  #     timeout: 300
  #     runas: root
# AfterInstall:
#   - location: scripts/start-container.sh
#     timeout: 180
